# Generated by Django 2.1.3 on 2019-02-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpagerelatedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagerelatedlink',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='blogpagerelatedlink',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
