# Generated by Django 2.1.3 on 2019-02-12 14:10

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(default='bai viet'),
            preserve_default=False,
        ),
    ]
