# Generated by Django 2.1.3 on 2019-02-16 06:15

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190215_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='author',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='feed_image',
            field=models.ForeignKey(blank=True, help_text='Hình theo chiều ngang, kích thước > 1000 px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
