# Generated by Django 2.1.3 on 2019-02-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190215_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Name'),
        ),
    ]
