# Generated by Django 2.1.3 on 2018-11-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Xét nghiệm', 'verbose_name_plural': 'Xét nghiệm'},
        ),
        migrations.AlterModelOptions(
            name='testcategory',
            options={'verbose_name': 'Nhóm xét nghiệm', 'verbose_name_plural': 'Nhóm xét nghiệm'},
        ),
        migrations.AddField(
            model_name='test',
            name='publish',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
