# Generated by Django 2.1.3 on 2018-11-21 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181120_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('message', models.TextField()),
                ('responded', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Yêu cầu liên hệ',
                'verbose_name_plural': 'Yêu cầu liên hệ',
            },
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.TestCategory', verbose_name='Nhóm xét nghiệm'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên xét nghiệm'),
        ),
        migrations.AlterField(
            model_name='test',
            name='referance_range',
            field=models.CharField(max_length=100, verbose_name='Reference range'),
        ),
        migrations.AlterField(
            model_name='test',
            name='sample_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại mẫu'),
        ),
    ]
