# Generated by Django 2.1.3 on 2018-11-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181121_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='slug',
            field=models.SlugField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
