# Generated by Django 2.1.3 on 2018-11-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181124_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
