# Generated by Django 2.1.3 on 2018-11-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181126_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='related_post',
            field=models.URLField(blank=True, null=True, verbose_name='Bài viết liên quan'),
        ),
    ]
