# Generated by Django 2.1.3 on 2018-11-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_test_related_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
